---
- name: copy tomcat.service file to /etc/systemd/system
  ansible.builtin.copy:
    src: files/tomcat.service
    dest: /etc/systemd/system/tomcat.service
    owner: root
    group: root
    mode: '0644'